{%- raw -%}
language: python
python: 2.7
sudo: false
env:
  matrix:
    - TOXENV=check
{% for env, config in tox_environments|dictsort %}
    - TOXENV={{ env }}{% if config.cover %}{% endraw %}{% if cookiecutter.c_extension_support|lower == "yes" %},extension-coveralls{% endif %}{% raw %},coveralls{% endif %}

{% endfor %}
before_install:
  - python --version
  - virtualenv --version
  - pip --version
  - uname -a
  - lsb_release -a
install:
  - pip install tox
script:
  - tox -v
notifications:
  email:
    on_success: never
    on_failure: always
{% endraw %}
